---
common_packages:
  - zsh
  - git
  - git-lfs
  - stow
  - tmux
  - wget
  - curl
  - unzip
  - fontconfig
  - software-properties-common
  - ripgrep
  - fastfetch
  - flameshot

dev_tool_packages:
  - golang
  - nodejs
  - npm
  - python3
  - python3-venv
  - pipx

ghostty_install_url: "https://raw.githubusercontent.com/mkasberg/ghostty-ubuntu/HEAD/install.sh"

chrome_url: "https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb"

ssh_packages:
  - openssh-server
  - ufw

xrdp_packages:
  - xrdp

qemu_packages:
  - qemu-guest-agent

sunshine_deb_url: "https://github.com/LizardByte/Sunshine/releases/latest/download/sunshine-ubuntu-24.04-amd64.deb"
