---
- name: Include macOS Docker tasks
  ansible.builtin.include_tasks: macos.yml
  when: "'macos' in group_names"

- name: Include Debian Docker tasks
  ansible.builtin.include_tasks: debian.yml
  when: "'debian' in group_names"

- name: Include Fedora Docker tasks
  ansible.builtin.include_tasks: fedora.yml
  when: "'fedora' in group_names"
