---
- name: Include macOS font tasks
  ansible.builtin.include_tasks: macos.yml
  when: "'macos' in group_names"

- name: Include Linux font tasks
  ansible.builtin.include_tasks: linux.yml
  when: "'macos' not in group_names"
