---
- name: Include macOS ghostty tasks
  ansible.builtin.include_tasks: macos.yml
  when: "'macos' in group_names"

- name: Include Debian ghostty tasks
  ansible.builtin.include_tasks: debian.yml
  when: "'debian' in group_names"

- name: Include Fedora ghostty tasks
  ansible.builtin.include_tasks: fedora.yml
  when: "'fedora' in group_names"
